---
apiVersion: v1
kind: Pod
spec:
  hostAliases:
  - ip: "172.19.90.206"
    hostnames:
    - "dev.eagle.norcom.de"
  - ip: "172.20.1.116"
    hostnames:
    - "dc1.norcom.de"
  volumes:
  - name: volume-0
    configMap:
      name: nexus-maven
  containers:
  - name: maven
    image: maven:3.6.3-openjdk-11-slim
    command:
    - cat
    tty: true
    volumeMounts:
    - name: volume-0
      mountPath: /root/.m2