---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-css
  namespace: devops-tools
data:
  dasense_norcom.css: |-
{{ .Files.Get "config-files/dasense_norcom.css" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-maven
  namespace: devops-tools
data:
  settings.xml: |-
{{ .Files.Get "config-files/settings.xml" | indent 4 }}