---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssh-keys
  namespace: devops-tools
type: Opaque
data:
  deploy-key-shared-library: {{ b64enc (.Files.Get "secret-files/deploy-key-shared-library") }}
  ssh-agent-access-key: {{ b64enc (.Files.Get "secret-files/ssh-agent-access-key") }}
  ssh-agent-access-key.pub: {{ b64enc (.Files.Get "secret-files/ssh-agent-access-key.pub") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-basic-auth-credentials
  namespace: devops-tools
type: Opaque
data:
  gitlab-ci-user: {{ b64enc (.Files.Get "secret-files/gitlab-ci-user") }}
  gitlab-ci-password: {{ b64enc (.Files.Get "secret-files/gitlab-ci-password") }}
  default-setup-user: {{ b64enc (.Files.Get "secret-files/default-setup-user") }}
  default-setup-password: {{ b64enc (.Files.Get "secret-files/default-setup-password") }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-tokens
  namespace: devops-tools
type: Opaque
data:
  slack-token: {{ b64enc (.Files.Get "secret-files/slack-token") }}
  gitlab-ci-token: {{ b64enc (.Files.Get "secret-files/gitlab-ci-token") }}