---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  namespace: devops-tools
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "fullname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
