---
image:
  pullPolicy: Always # set to Never if u don't use docker registr
  repository: nexus-docker.local:32489/devops-tools/jenkins-as-code
  tag: 2.164.3
  pullSecrets: docregsecret
persistence:
  claimName: jenkins-pvc
  accessMode: ReadWriteOnce
  enabled: true
  size: 5Gi
  storageClass: rook-ceph-block
serviceType: ClusterIP